chore: format messages according to the latest UX guidelines and technical writing standards by Google, Microsoft, and the Nielsen Norman Group

diff --git a/minecraft-pack-build b/minecraft-pack-build
--- a/minecraft-pack-build
+++ b/minecraft-pack-build
@@ -123,8 +123,9 @@ log_message() {
   local _line_append="\n"
   local _text
   local _status=""
-  while [[ "${1:-}" != "" ]]; do
-    case ${1} in
+  local POSITIONAL_ARGS=()
+  while [[ $# -gt 0 ]]; do
+    case $1 in
     -c | --color)
       shift
       _color_value="$(styler text "$1")"
@@ -150,10 +151,11 @@ log_message() {
       shift
       _status="$1"
       ;;
-    *) break ;;
+    *) POSITIONAL_ARGS+=("$1") ;;
     esac
     shift
   done
+  set -- "${POSITIONAL_ARGS[@]}"
   # shellcheck disable=SC2059
   _text="$(_text_format "$_color_value" "$@")"
   if [[ -n "$_icon" ]]; then
@@ -177,8 +179,9 @@ prepare_log_message() {
   shift
   local _icon="$1"
   shift
-  while [[ "${1:-}" != "" ]]; do
-    case ${1} in
+  local POSITIONAL_ARGS=()
+  while [[ $# -gt 0 ]]; do
+    case $1 in
     -c | --color)
       shift
       _color="$1"
@@ -187,23 +190,24 @@ prepare_log_message() {
       shift
       _icon="$1"
       ;;
-    *) break ;;
+    *) POSITIONAL_ARGS+=("$1") ;;
     esac
     shift
   done
+  set -- "${POSITIONAL_ARGS[@]}"
   log_message --color "$_color" --icon "$_icon" "$@"
 }
 
 log_info() {
-  prepare_log_message "CYAN" "$ICON_INFO" "$@"
+  prepare_log_message 'CYAN' "$ICON_INFO" "$@"
 }
 
 log_success() {
-  prepare_log_message "GREEN" "$ICON_SUCCESS" "$@"
+  prepare_log_message 'GREEN' "$ICON_SUCCESS" "$@"
 }
 
 log_warning() {
-  prepare_log_message "BLUE" "$ICON_WARNING" "$@"
+  prepare_log_message 'BLUE' "$ICON_WARNING" "$@"
 }
 
 log_error() {
@@ -238,7 +242,7 @@ log_title() {
   local _padding=$(((_total_width - _title_length) / 2))
 
   log_message --color "WHITE" "<b>╔%s╗</b>" "$(printf "═%.0s" $(seq 1 1 $_total_width))"
-  log_message --color "WHITE" "<b>║%*s$(styler text "YELLOW")%s%*s$(styler text "WHITE")║</b>" $_padding "" "$_title_text" $_padding ""
+  log_message --color "WHITE" "<b>║%*s$(styler text "YELLOW")%s%*s$(styler text "WHITE")║</b>" "$_padding" " " "$_title_text" "$_padding" " "
   log_message --color "WHITE" "<b>╚%s╝</b>" "$(printf "═%.0s" $(seq 1 1 $_total_width))"
 }
 
@@ -251,113 +255,106 @@ log_usage_line() {
 }
 
 log_usage_options_line() {
-  local description="$1"
+  local _description="$1"
   shift
-  local parameters
-  parameters="$(printf "%s, " "$@")"
-  log_message "  <b>%-*s</b> %s" "30" "${parameters::-2}" "$description"
+  local _parameters
+  _parameters="$(printf "%s, " "$@")"
+  log_message '  <b>%-*s</b> %s' "30" "${_parameters::-2}" "$_description"
 }
 
 log_usage_example_line() {
-  log_message --color "CYAN" --icon " \$" "<code>%s</code>" "$@"
+  log_message --color 'CYAN' --icon ' $' '<code>%s</code>' "$@"
 }
 
 # Die with error message
 die() {
+  local _error_code="$1"
+  shift
   log_error "$@"
-  exit 1
+  exit "$_error_code"
 }
 
 ##----Loading animation------------------------------------------------------------------------------------------------------------
+loading_animation_pid=""
+loading_animation_message=""
 
-play_loading_animation_loop() {
-  while [ $# -gt 0 ]; do
+loading_animation_loop() {
+  local _exit_code=0
+  local _exit_trap=0
+  local _status=""
+  local POSITIONAL_ARGS=()
+  while [[ $# -gt 0 ]]; do
     case $1 in
-    -t | --time)
-      shift
-      loading_animation_timer="$1"
-      ;;
     -m | --message)
       shift
       loading_animation_message="$1"
       ;;
+    -t | --time)
+      shift
+      countdown="$1"
+      ;;
+    -c | --_exit_code)
+      shift
+      _exit_code="$1"
+      ;;
+    -s | --status)
+      shift
+      _status="$1"
+      ;;
+    -x) _exit_trap=1 ;;
+    *) POSITIONAL_ARGS+=("$1") ;;
     esac
     shift
   done
-  (
-    _step=0
-    while true; do
-      for _frame in "${LOADING_ANIMATION[@]}"; do
-        if [[ "$loading_animation_message" != "" ]]; then
-          log_message --color "CYAN" --one-line --icon "$_frame" "$loading_animation_message"
-          sleep "$LOADING_ANIMATION_FRAME_INTERVAL"
-        else
-          log_message --color "CYAN" --one-line "waiting %s" "$(echo "$loading_animation_timer - $_step" | bc -z)"
-          sleep "1"
-        fi
-        _step="$((_step + 1))"
-        printf "\r"
-      done
-    done
-  ) &
-  loading_animation_pid=$!
-}
-
-kill_loading_animation_loop() {
-  if [[ -n "${loading_animation_pid:-}" ]]; then
+  set -- "${POSITIONAL_ARGS[@]}"
+  if [[ -n "$loading_animation_pid" ]]; then
     kill "$loading_animation_pid" &>/dev/null
     printf "\r%100s\r$(styler reset)" ""
-    code=0
-    status=""
-    while [ $# -gt 0 ]; do
-      case $1 in
-      -c | --code)
-        shift
-        code="$1"
-        ;;
-      -s | --status)
-        shift
-        status="$1"
-        ;;
-      -m | --message)
-        shift
-        loading_animation_message="$1"
-        ;;
-      esac
-      shift
-    done
     if [[ "$loading_animation_message" != "" ]]; then
-      if [[ "$code" -gt "0" ]]; then
-        log_error --status "$status" "$loading_animation_message"
-      elif [[ "$code" -lt "0" ]]; then
-        log_warning --status "$status" "$loading_animation_message"
+      if [[ "$_exit_code" -gt "0" ]]; then
+        log_error --status "$_status" "$loading_animation_message" "$@"
+      elif [[ "$_exit_code" -lt "0" ]]; then
+        log_warning --status "$_status" "$loading_animation_message" "$@"
       else
-        log_success --status "$status" "$loading_animation_message"
+        log_success --status "$_status" "$loading_animation_message" "$@"
       fi
+      loading_animation_pid=""
+      loading_animation_message=""
     fi
-    loading_animation_pid=""
-    loading_animation_message=""
-    loading_animation_timer=""
+  elif [[ "$_exit_trap" -eq "0" ]]; then
+    (
+      _step=0
+      while true; do
+        for _frame in "${LOADING_ANIMATION[@]}"; do
+          if [[ -n "$loading_animation_message" ]]; then
+            log_message --color "CYAN" --one-line --icon "$_frame" "$loading_animation_message"
+            sleep "$LOADING_ANIMATION_FRAME_INTERVAL"
+          else
+            log_message --color "CYAN" --one-line "waiting %s" "$(echo "$countdown - $_step" | bc -z)"
+            sleep "1"
+          fi
+          _step="$((_step + 1))"
+          printf "\r"
+        done
+      done
+    ) &
+    loading_animation_pid=$!
   fi
 }
 
 wait_moment() {
-  play_loading_animation_loop --time "$RETRY_INTERVAL"
+  loading_animation_loop --time "$RETRY_INTERVAL"
   sleep "$RETRY_INTERVAL"
-  kill_loading_animation_loop --code 0
+  loading_animation_loop --code 0
 }
 
-trap "kill_loading_animation_loop;exit" SIGINT
-trap "kill_loading_animation_loop;exit" EXIT
+trap "loading_animation_loop -x;exit" SIGINT
+trap "loading_animation_loop -x;exit" EXIT
 
 ##----Helpers------------------------------------------------------------------------------------------------------------
 
-to_title_case() {
-  echo "$1" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++){sub(/./,toupper(substr($i,1,1)),$i)}print}'
-}
-
-array_to_string() {
-  echo "$1" | jq -r 'join(".")'
+normalize_name() {
+  echo "$1" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++){sub(/./,toupper(substr($i,1,1)),$i)}print}' | sed 's/Minecraft Bedrock Addon//g' | sed 's/  / /g'
 }
 
 get_wildcard_filename() {
@@ -386,6 +383,10 @@ get_output_dir_name() {
   echo "$(realpath "${OUTPUT_DIR%/}")/"
 }
 
+array_to_string() {
+  echo "$1" | jq -r 'join(".")'
+}
+
 ##----Version------------------------------------------------------------------------------------------------------------
 
 get_version_string() {
@@ -403,7 +404,7 @@ get_shared_version() {
   if [[ -f "$_version_file" ]]; then
     array_to_string "$(jq -r '.version' "$_version_file")"
   else
-    die "Version <b>$_version_file</b> file not found" 31
+    die 31 "Version file not found: <b>%s</b>." "$_version_file"
   fi
 }
 
@@ -440,7 +441,7 @@ bump_versions() {
   _rp_uuid="$(echo "$_rp_content" | jq -r '.header.uuid')"
 
   # Get current shared version and bump it
-  play_loading_animation_loop -m "Bumping shared version for BP and RP"
+  loading_animation_loop -m "Bumping shared version for BP and RP"
   local _current_shared_version
   _current_shared_version=$(jq -r '.version' "${INPUT_DIR}version.json" 2>/dev/null || echo '[1, 0, 0]')
   local _new_shared_version
@@ -448,81 +449,81 @@ bump_versions() {
 
   # Update shared version file
   set_shared_version "$_new_shared_version"
-  kill_loading_animation_loop -m "Bumped version to $(array_to_string "$_new_shared_version")"
+  loading_animation_loop -m "Bumped version to %s" "$(array_to_string "$_new_shared_version")"
 
   # Update BP manifest
-  play_loading_animation_loop -m "Saving BP version"
+  loading_animation_loop -m "Saving BP version"
   _bp_content=$(echo "$_bp_content" | jq --argjson ver "$_new_shared_version" '.header.version = $ver')
   _bp_content=$(echo "$_bp_content" | jq --argjson ver "$_new_shared_version" '(.dependencies[]? | select(.uuid == "'"$_rp_uuid"'") | .version) = $ver')
   echo "$_bp_content" >"$_bp_path"
-  kill_loading_animation_loop -m "Saved BP version"
+  loading_animation_loop -m "Saved BP version"
 
   # Update RP manifest
-  play_loading_animation_loop -m "Saving RP version"
+  loading_animation_loop -m "Saving RP version"
   _rp_content=$(echo "$_rp_content" | jq --argjson ver "$_new_shared_version" '.header.version = $ver')
   _rp_content=$(echo "$_rp_content" | jq --argjson ver "$_new_shared_version" '(.dependencies[]? | select(.uuid == "'"$_bp_uuid"'") | .version) = $ver')
   echo "$_rp_content" >"$_rp_path"
-  kill_loading_animation_loop -m "Saved RP version"
+  loading_animation_loop -m "Saved RP version"
 }
 
 ##----Build------------------------------------------------------------------------------------------------------------
 
 build_mcaddon() {
-  play_loading_animation_loop -m "Preparing MCADDON configuration"
+  loading_animation_loop -m "Preparing MCADDON configuration"
   MC_ADDON_FILE_PATH="$(get_filename "mcaddon")"
   find "${GET_OUTPUT_DIR_NAME}" -name "$(get_wildcard_filename "mcaddon")" -type f -exec rm {} \;
-  kill_loading_animation_loop -m "Prepared MCADDON configuration" -s "$GET_OUTPUT_DIR_NAME"
+  loading_animation_loop -m "Prepared MCADDON configuration" -s "$GET_OUTPUT_DIR_NAME"
 
-  play_loading_animation_loop -m "Creating MCADDON"
+  loading_animation_loop -m "Creating MCADDON"
   if (cd "$INPUT_DIR" && zip -qr "${GET_OUTPUT_DIR_NAME}${MC_ADDON_FILE_PATH}" "$BP_DIR" "$RP_DIR"); then
-    kill_loading_animation_loop -m "Created MCADDON" -s "${GET_OUTPUT_DIR_NAME}${MC_ADDON_FILE_PATH}"
+    loading_animation_loop -m "Created MCADDON" -s "${GET_OUTPUT_DIR_NAME}${MC_ADDON_FILE_PATH}"
   else
-    kill_loading_animation_loop -m "Failed to create MCADDON" -c "$?"
+    loading_animation_loop -m "Failed to create MCADDON" -c "$?"
   fi
 }
 
 build_mcpack() {
-  play_loading_animation_loop -m "Preparing MCPACK configuration"
+  loading_animation_loop -m "Preparing MCPACK configuration"
   MC_PACK_BP_FILE_PATH="$(get_filename "mcpack" "BP")"
   MC_PACK_RP_FILE_PATH="$(get_filename "mcpack" "RP")"
   find "${GET_OUTPUT_DIR_NAME}" -name "$(get_wildcard_filename "mcpack" "BP")" -type f -exec rm {} \;
   find "${GET_OUTPUT_DIR_NAME}" -name "$(get_wildcard_filename "mcpack" "RP")" -type f -exec rm {} \;
-  kill_loading_animation_loop -m "Prepared MCPACK configuration" -s "$GET_OUTPUT_DIR_NAME"
+  loading_animation_loop -m "Prepared MCPACK configuration" -s "$GET_OUTPUT_DIR_NAME"
 
-  play_loading_animation_loop -m "Creating behavior MCPACK"
+  loading_animation_loop -m "Creating behavior MCPACK"
   if (cd "$INPUT_DIR$BP_DIR" && zip -qr "${GET_OUTPUT_DIR_NAME}${MC_PACK_BP_FILE_PATH}" .); then
-    kill_loading_animation_loop -m "Created behavior MCPACK" -s "$MC_PACK_BP_FILE_PATH"
+    loading_animation_loop -m "Created behavior MCPACK" -s "$MC_PACK_BP_FILE_PATH"
   else
-    kill_loading_animation_loop -m "Failed to create behavior MCPACK" -c "$?"
+    loading_animation_loop -m "Failed to create behavior MCPACK" -c "$?"
   fi
 
-  play_loading_animation_loop -m "Creating resource MCPACK"
+  loading_animation_loop -m "Creating resource MCPACK"
   if (cd "$INPUT_DIR$RP_DIR" && zip -qr "${GET_OUTPUT_DIR_NAME}${MC_PACK_RP_FILE_PATH}" .); then
-    kill_loading_animation_loop -m "Created resource MCPACK" -s "$MC_PACK_RP_FILE_PATH"
+    loading_animation_loop -m "Created resource MCPACK" -s "$MC_PACK_RP_FILE_PATH"
   else
-    kill_loading_animation_loop -m "Failed to create resource MCPACK" -c "$?"
+    loading_animation_loop -m "Failed to create resource MCPACK" -c "$?"
   fi
 }
 
 install_locally() {
   if [[ ! -d "$MOJANG_DIR" ]]; then
-    die "Local mojang path <u>$MOJANG_DIR</u> does not exist." 32
+    die 32 "Local mojang path does not exist: <u>%s</u>." "$MOJANG_DIR"
   fi
 
-  play_loading_animation_loop -m "Preparing installation"
+  loading_animation_loop -m "Preparing installation"
   find "${MOJANG_DIR}behavior_packs/" -name "$(get_wildcard_filename "mcpack" "BP")" -type f -exec rm {} \;
   find "${MOJANG_DIR}resource_packs/" -name "$(get_wildcard_filename "mcpack" "RP")" -type f -exec rm {} \;
-  kill_loading_animation_loop -m "Prepared installation" -s "$MOJANG_DIR"
+  loading_animation_loop -m "Prepared installation" -s "$MOJANG_DIR"
 
-  play_loading_animation_loop -m "Installing BP on local"
+  loading_animation_loop -m "Installing BP on local"
   mkdir -p "${MOJANG_DIR}behavior_packs/"
   cp -r "${GET_OUTPUT_DIR_NAME}${MC_PACK_BP_FILE_PATH}" "${MOJANG_DIR}behavior_packs/"
-  kill_loading_animation_loop -m "Installed BP on local" -s "behavior_packs/${MC_PACK_BP_FILE_PATH}"
+  loading_animation_loop -m "Installed BP on local" -s "behavior_packs/${MC_PACK_BP_FILE_PATH}"
 
-  play_loading_animation_loop - "Installing RP on local"
+  loading_animation_loop - "Installing RP on local"
   mkdir -p "${MOJANG_DIR}resource_packs/"
   cp -r "${GET_OUTPUT_DIR_NAME}${MC_PACK_RP_FILE_PATH}" "${MOJANG_DIR}resource_packs/"
-  kill_loading_animation_loop -m "Installed RP on local" -s "resource_packs/${MC_PACK_RP_FILE_PATH}"
+  loading_animation_loop -m "Installed RP on local" -s "resource_packs/${MC_PACK_RP_FILE_PATH}"
 }
 
 ##----Parser------------------------------------------------------------------------------------------------------------
@@ -573,6 +574,29 @@ parse_arguments() {
   fi
 }
 
+##----Checking------------------------------------------------------------------------------------------------------------
+
+# Check if command exists
+command_exists() {
+  command -v "$1" >/dev/null 2>&1
+}
+
+check_dependencies() {
+  local deps=("$@")
+  local missing_deps=()
+
+  for dep in "${deps[@]}"; do
+    if ! command_exists "$dep"; then
+      missing_deps+=("$dep")
+    fi
+  done
+
+  if [[ ${#missing_deps[@]} -gt 0 ]]; then
+    missing_items="$(printf "<b>%s</b>, " "${missing_deps[@]}")"
+    die 13 "Missing dependencies: %s. Please install them and try again." "${missing_items::-2}"
+  fi
+}
+
 ## ##----Configuration------------------------------------------------------------------------------------------------------------
 
 declare -r BP_DIR="BP/"
@@ -602,38 +626,37 @@ if [[ $MCADDON -ne 1 && $MCPACK -ne 1 && $INSTALL_ON_LOCAL -ne 1 ]]; then
   show_usage
 fi
 if [[ -z "$INPUT_DIR" ]]; then
-  die "Source directory is not defined." 11
+  die 11 "Source directory is not defined."
 fi
 if [[ ! -d "$INPUT_DIR" ]]; then
-  die "Source directory <u>$INPUT_DIR</u> does not exist." 12
+  die 12 "Source directory <u>%s</u> does not exist." "$INPUT_DIR"
 fi
 if [[ ! -d "$OUTPUT_DIR" ]]; then
   if [[ "$OUTPUT_DIR_FORCE" -eq 1 ]]; then
     mkdir "$OUTPUT_DIR"
     log_info "Created output directory" "$OUTPUT_DIR"
   else
-    die "Output directory <u>$OUTPUT_DIR</u> does not exist. Add <b>--force</b> argument to create missing directory or give another." 13
+    die 13 "Output directory does not exist: <u>%s</u>. Add <b>--force</b> argument to create missing directory or give another." "$OUTPUT_DIR"
   fi
 fi
 if [[ $INSTALL_ON_LOCAL -eq 1 ]] && [[ ! -d "$MOJANG_DIR" ]]; then
-  die "Mojang directory <u>$MOJANG_DIR</u> does not exist." 14
+  die 14 "Mojang directory does not exist: <u>%s</u>." "$MOJANG_DIR"
 
 fi
 
 GET_OUTPUT_DIR_NAME="$(get_output_dir_name)"
 if [[ ! -f "${INPUT_DIR}version.json" ]]; then
-  die "Source directory <u>${INPUT_DIR}</u> does not contain <u>version.json</u> file." 21
+  die 21 "Source directory does not contain <u>version.json</u> file: <u>%s</u>" "$INPUT_DIR"
 fi
 if [[ ! -f "${INPUT_DIR}${BP_DIR}manifest.json" ]]; then
-  die "Source directory <u>${INPUT_DIR}${BP_DIR}</u> does not contain <u>manifest.json</u> file." 22
+  die 22 "Source directory does not contain <u>manifest.json</u> file: <u>%s</u>" "${INPUT_DIR}${BP_DIR}"
 fi
 if [[ ! -f "${INPUT_DIR}${RP_DIR}manifest.json" ]]; then
-  die "Source directory <u>${INPUT_DIR}${RP_DIR}</u> does not contain <u>manifest.json</u> file." 23
+  die 23 "Source directory does not contain <u>manifest.json</u> file: <u>%s</u>." "${INPUT_DIR}${RP_DIR}"
 fi
 
-PACKNAME="$(cd "$INPUT_DIR" && basename "$(pwd)")"
-PACKNAME="$(to_title_case "$PACKNAME")"
-log_header "Building Minecraft packs for <b>$PACKNAME</b> project"
+PACKNAME="$(normalize_name "$(cd "$INPUT_DIR" && basename "$(pwd)")")"
+log_header "Building Minecraft packs for <b>%s</b> project" "$PACKNAME"
 
 if [[ $VERSION_BUMP -eq 1 ]]; then
   bump_versions
