fix: build script optimization

diff --git a/minecraft-pack-build b/minecraft-pack-build
--- a/minecraft-pack-build
+++ b/minecraft-pack-build
@@ -5,33 +5,13 @@
 
 set -euo pipefail
 
-##----COLORS------------------------------------------------------------------------------------------------------------
-
-declare -r FCOLOR_BLACK="$(tput setaf 0)"
-declare -r FCOLOR_RED="$(tput setaf 1)"
-declare -r FCOLOR_GREEN="$(tput setaf 2)"
-declare -r FCOLOR_YELLOW="$(tput setaf 3)"
-declare -r FCOLOR_BLUE="$(tput setaf 4)"
-declare -r FCOLOR_PURPLE="$(tput setaf 5)"
-declare -r FCOLOR_CYAN="$(tput setaf 6)"
-declare -r FCOLOR_WHITE="$(tput setaf 7)"
-declare -r FORMAT_BOLD="$(tput bold)"
-declare -r FORMAT_RESET="$(tput sgr0)"
-declare -r ICON_INFO='ℹ'
-declare -r ICON_SUCCESS='✔'
-declare -r ICON_WARNING='⚠'
-declare -r ICON_ERROR='✘'
-declare -r LOADING_ANIMATION=(⠇ ⠋ ⠙ ⠸ ⠴ ⠦)
-declare -r LOADING_ANIMATION_FRAME_INTERVAL=0.15
-
-loading_animation_message=""
-loading_animation_timer=""
-loading_animation_pid=""
+# Set terminal type for proper color support
+export TERM=xterm-256color
 
 ##----USAGE------------------------------------------------------------------------------------------------------------
 
 show_usage() {
-  echo -e "${FORMAT_BOLD}Usage${FORMAT_RESET}: ${FCOLOR_PURPLE}$0 [OPTIONS]$FORMAT_RESET"
+  log_usage_line "$0 [OPTIONS]"
   echo
   log_header "Options"
   log_usage_options_line "input directory location" "-i" "--input DIR"
@@ -57,10 +37,240 @@ show_usage() {
   echo
   exit 0
 }
+##----Check bash version------------------------------------------------------------------------------------------------------------
 
-##----FUNCTIONS------------------------------------------------------------------------------------------------------------
+if [[ "$BASH_VERSION" == 0* ]] || [[ "$BASH_VERSION" == 1* ]] || [[ "$BASH_VERSION" == 2* ]] || [[ "$BASH_VERSION" == 3* ]]; then
+  echo "Bash version is too low. Consider upgrading to bash newer than $BASH_VERSION"
+  if uname | grep -iq Darwin; then
+    echo "Read more on https://itnext.io/upgrading-bash-on-macos-7138bd1066ba"
+  fi
+  exit 9
+fi
 
-function play_loading_animation_loop() {
+# Set terminal type for proper color support
+export TERM=xterm-256color
+shopt -s extglob
+
+##----Formatting------------------------------------------------------------------------------------------------------------
+
+styler() {
+  case "$1" in
+  font | text | FONT | TEXT)
+    case "$2" in
+    black | BLACK) tput setaf 0 ;;
+    red | RED) tput setaf 1 ;;
+    green | GREEN) tput setaf 2 ;;
+    yellow | YELLOW) tput setaf 3 ;;
+    blue | BLUE) tput setaf 4 ;;
+    purple | PURPLE) tput setaf 5 ;;
+    cyan | CYAN) tput setaf 6 ;;
+    white | WHITE) tput setaf 7 ;;
+    *) tput setaf 9 ;;
+    esac
+    ;;
+  bg | background | BG | BACKGROUND)
+    case "$2" in
+    reset | REST) tput sgr0 ;;
+    black | BLACK) tput setab 0 ;;
+    red | RED) tput setab 1 ;;
+    green | GREEN) tput setab 2 ;;
+    yellow | YELLOW) tput setab 3 ;;
+    blue | BLUE) tput setab 4 ;;
+    purple | PURPLE) tput setab 5 ;;
+    cyan | CYAN) tput setab 6 ;;
+    white | WHITE) tput setab 7 ;;
+    *) tput setab 9 ;;
+    esac
+    ;;
+  bold | BOLD) tput bold ;;
+  reset | REST) tput sgr0 ;;
+  esac
+}
+
+# Icons
+readonly ICON_INFO='☞'
+readonly ICON_SUCCESS='✓'
+readonly ICON_WARNING='‼'
+readonly ICON_ERROR='✗'
+readonly ICON_DEBUG=''
+readonly ICON_PROMPT='↳'
+
+readonly LOADING_ANIMATION=("⠇" "⠋" "⠙" "⠸" "⠴" "⠦")
+readonly LOADING_ANIMATION_FRAME_INTERVAL=0.15
+
+##----Display line------------------------------------------------------------------------------------------------------------
+
+log_message() {
+  function _text_format() {
+    local _color_value="$1"
+    shift
+    local _pattern="$1"
+    shift
+    local _text
+    # shellcheck disable=SC2059
+    _text=$(printf -- "$_pattern" "$@")
+    _text=${_text//<b>/$(styler bold)${_color_value}}
+    _text=${_text//<\/b>/$(styler reset)${_color_value}}
+    _text=${_text//<u>/$(tput smul)${_color_value}}
+    _text=${_text//<\/u>/$(tput rmul)${_color_value}}
+    _text=${_text//<code>/$(styler bg "CYAN")$(styler text "BLACK")}
+    _text=${_text//<\/code>/$(styler reset)${_color_value}}
+    echo -e "$_text"
+  }
+  local _color_value=""
+  local _icon=""
+  local _line_prepend=""
+  local _line_append="\n"
+  local _text
+  local _status=""
+  while [[ "${1:-}" != "" ]]; do
+    case ${1} in
+    -c | --color)
+      shift
+      _color_value="$(styler text "$1")"
+      ;;
+    -i | --icon)
+      shift
+      _icon="$1"
+      ;;
+    -p | --prepend)
+      shift
+      _line_prepend="$_line_prepend$1"
+      ;;
+    -b | --bell)
+      _line_prepend="$_line_prepend\a"
+      ;;
+    -r | --reset)
+      _line_prepend="\r$_line_prepend"
+      ;;
+    -o | --one-line)
+      _line_append=""
+      ;;
+    -s | --status)
+      shift
+      _status="$1"
+      ;;
+    *) break ;;
+    esac
+    shift
+  done
+  # shellcheck disable=SC2059
+  _text="$(_text_format "$_color_value" "$@")"
+  if [[ -n "$_icon" ]]; then
+    _text="$(_text_format "$_color_value" " <b>%s</b> %s" "$_icon" "$_text")"
+  fi
+  if [[ -n "$_status" ]]; then
+    local _raw_bytes
+    _raw_bytes="$(echo -n "${_text//$'\e'[\[(]*([0-9;])[@-n]/}" | wc -c | tr -d ' ')"
+    local _text_bytes
+    _text_bytes="$(echo -n "$_text" | wc -c | tr -d ' ')"
+    local _text_chars
+    _text_chars="$(echo -n "$_text" | wc -m | tr -d ' ')"
+    local _padding=$((64 + (_text_bytes - _text_chars) + (_text_bytes - _raw_bytes)))
+    _text="$(_text_format "$_color_value" "%-*s [<b>%s</b>]" "$_padding" "$_text" "$_status")"
+  fi
+  echo -e -n "${_line_prepend}${_color_value}${_text}${_line_append}$(styler reset)"
+}
+
+prepare_log_message() {
+  local _color="$1"
+  shift
+  local _icon="$1"
+  shift
+  while [[ "${1:-}" != "" ]]; do
+    case ${1} in
+    -c | --color)
+      shift
+      _color="$1"
+      ;;
+    -i | --icon)
+      shift
+      _icon="$1"
+      ;;
+    *) break ;;
+    esac
+    shift
+  done
+  log_message --color "$_color" --icon "$_icon" "$@"
+}
+
+log_info() {
+  prepare_log_message "CYAN" "$ICON_INFO" "$@"
+}
+
+log_success() {
+  prepare_log_message "GREEN" "$ICON_SUCCESS" "$@"
+}
+
+log_warning() {
+  prepare_log_message "BLUE" "$ICON_WARNING" "$@"
+}
+
+log_error() {
+  prepare_log_message "RED" "$ICON_ERROR" "$@"
+}
+
+log_debug() {
+  if [[ "${DEBUG:-0}" == "1" || "${debug:-0}" == "1" ]]; then
+    prepare_log_message "PURPLE" "$ICON_DEBUG" "$@"
+  fi
+}
+
+log_title() {
+  local _title="$1"
+  local _version="${2:-}"
+  local _title_text
+  if [[ -n "$_version" ]]; then
+    _title_text="${_title} v${_version}"
+  else
+    _title_text="${_title}"
+  fi
+
+  # Calculate padding to center the title
+  local _title_length=${#_title_text}
+  local _total_width=64
+  if [[ "$_title_length" -gt "$_total_width" ]]; then
+    _total_width=$((_title_length + 4))
+  fi
+  if [[ $((_title_length % 2)) -eq 1 ]]; then
+    _total_width="$((_total_width - 1))"
+  fi
+  local _padding=$(((_total_width - _title_length) / 2))
+
+  log_message --color "WHITE" "<b>╔%s╗</b>" "$(printf "═%.0s" $(seq 1 1 $_total_width))"
+  log_message --color "WHITE" "<b>║%*s$(styler text "YELLOW")%s%*s$(styler text "WHITE")║</b>" $_padding "" "$_title_text" $_padding ""
+  log_message --color "WHITE" "<b>╚%s╝</b>" "$(printf "═%.0s" $(seq 1 1 $_total_width))"
+}
+
+log_header() {
+  log_message --color "PURPLE" "<b>%s</b>" "$1"
+}
+
+log_usage_line() {
+  log_message --color "PURPLE" "<b>Usage</b> <code>$*</code>"
+}
+
+log_usage_options_line() {
+  local description="$1"
+  shift
+  local parameters
+  parameters="$(printf "%s, " "$@")"
+  log_message "  <b>%-*s</b> %s" "30" "${parameters::-2}" "$description"
+}
+
+log_usage_example_line() {
+  log_message --color "CYAN" --icon " \$" "<code>%s</code>" "$@"
+}
+
+# Die with error message
+die() {
+  log_error "$@"
+  exit 1
+}
+
+##----Loading animation------------------------------------------------------------------------------------------------------------
+
+play_loading_animation_loop() {
   while [ $# -gt 0 ]; do
     case $1 in
     -t | --time)
@@ -75,17 +285,17 @@ function play_loading_animation_loop() {
     shift
   done
   (
-    step=0
+    _step=0
     while true; do
-      for frame in "${LOADING_ANIMATION[@]}"; do
+      for _frame in "${LOADING_ANIMATION[@]}"; do
         if [[ "$loading_animation_message" != "" ]]; then
-          printf "%s" "$(format_message "$FCOLOR_BLUE" " <b>$frame</b> $loading_animation_message")"
+          log_message --color "CYAN" --one-line --icon "$_frame" "$loading_animation_message"
           sleep "$LOADING_ANIMATION_FRAME_INTERVAL"
         else
-          printf " waiting ${FCOLOR_BLUE}%s${FORMAT_RESET}s" "$(echo "$loading_animation_timer - $step" | bc -z)"
+          log_message --color "CYAN" --one-line "waiting %s" "$(echo "$loading_animation_timer - $_step" | bc -z)"
           sleep "1"
         fi
-        step="$((step + 1))"
+        _step="$((_step + 1))"
         printf "\r"
       done
     done
@@ -93,10 +303,10 @@ function play_loading_animation_loop() {
   loading_animation_pid=$!
 }
 
-function kill_loading_animation_loop() {
-  if [[ "$loading_animation_pid" != "" ]]; then
+kill_loading_animation_loop() {
+  if [[ -n "${loading_animation_pid:-}" ]]; then
     kill "$loading_animation_pid" &>/dev/null
-    printf "\r%100s\r${FORMAT_RESET}${FORMAT_RESET}" ""
+    printf "\r%100s\r$(styler reset)" ""
     code=0
     status=""
     while [ $# -gt 0 ]; do
@@ -118,11 +328,11 @@ function kill_loading_animation_loop() {
     done
     if [[ "$loading_animation_message" != "" ]]; then
       if [[ "$code" -gt "0" ]]; then
-        log_error "$loading_animation_message" "$status"
+        log_error --status "$status" "$loading_animation_message"
       elif [[ "$code" -lt "0" ]]; then
-        log_warning "$loading_animation_message" "$status"
+        log_warning --status "$status" "$loading_animation_message"
       else
-        log_success "$loading_animation_message" "$status"
+        log_success --status "$status" "$loading_animation_message"
       fi
     fi
     loading_animation_pid=""
@@ -131,7 +341,7 @@ function kill_loading_animation_loop() {
   fi
 }
 
-function wait_moment() {
+wait_moment() {
   play_loading_animation_loop --time "$RETRY_INTERVAL"
   sleep "$RETRY_INTERVAL"
   kill_loading_animation_loop --code 0
@@ -140,76 +350,43 @@ function wait_moment() {
 trap "kill_loading_animation_loop;exit" SIGINT
 trap "kill_loading_animation_loop;exit" EXIT
 
-format_message() {
-  local color="$1"
-  local message="$2"
-  message=${message//<b>/${FORMAT_BOLD}${color}}
-  message=${message//<\/b>/${FORMAT_RESET}${color}}
-  message=${message//<u>/$(tput smul)${color}}
-  message=${message//<\/u>/$(tput rmul)${color}}
-  echo -e "${color}${message}${FORMAT_RESET}"
+##----Helpers------------------------------------------------------------------------------------------------------------
+
+to_title_case() {
+  echo "$1" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++){sub(/./,toupper(substr($i,1,1)),$i)}print}'
 }
 
-log_message() {
-  local color
-  color="$(eval echo "\$FCOLOR_${1}")"
-  local icon
-  icon="$(eval echo "\$ICON_${2}")"
-  local message="$3"
-  local status="${4:-""}"
-  local len=32
-  local message_len=${#message}
-  if [[ "$message_len" -gt "$len" ]]; then
-    len="$((message_len + 4))"
+array_to_string() {
+  echo "$1" | jq -r 'join(".")'
+}
+
+get_wildcard_filename() {
+  local _extension="$1"
+  local _suffix="${2:-}"
+  echo -e "$PACKNAME*${_suffix}*.${_extension}"
+}
+
+get_filename() {
+  local _extension="$1"
+  local _suffix="${2:-}"
+  local _name="$PACKNAME"
+  if [[ $APPEND_VERSION_TO_BUILD_FILE -eq 1 ]]; then
+    _name+=" v$(get_shared_version)"
   fi
-  if [[ "$status" != "" ]]; then
-    format_message "$color" "$(printf " <b>%s</b> %-*s [<b>%s</b>]" "$icon" "$len" "$message" "$status")"
-  else
-    format_message "$color" "$(printf " <b>%s</b> %-*s" "$icon" $len "$message")"
+  if [[ $APPEND_TIME_TO_BUILD_FILE -eq 1 ]]; then
+    _name+=" $(date +"%Y%m%d%H%M%S")"
   fi
+  if [[ "$_suffix" != "" ]]; then
+    _name+=" $_suffix"
+  fi
+  echo "${_name}.${_extension}"
 }
 
-log_title() {
-  local title_text="$1"
-  local title_length=${#title_text}
-  total_width=$((title_length + 4))
-  local padding=$(((total_width - title_length) / 2))
-  border="$(printf "%*s" "$total_width" "" | tr " " "═")"
-  printf "╔%s╗\n" "$border"
-  printf "║%*s%s%*s║\n" "$padding" "" "$(format_message "$FCOLOR_YELLOW" "<b>$title_text</b>")" "$padding" ""
-  printf "╚%s╝\n" "$border"
-}
-log_header() {
-  format_message "${FORMAT_BOLD}${FCOLOR_WHITE}" "$1"
-}
-log_info() {
-  log_message "BLUE" "INFO" "$1" "${2:-""}"
-}
-log_success() {
-  log_message "GREEN" "SUCCESS" "$1" "${2:-""}"
-}
-log_warning() {
-  log_message "YELLOW" "WARNING" "$1" "${2:-""}"
-}
-log_error() {
-  log_message "RED" "ERROR" "$1" "${2:-""}"
-}
-die() {
-  log_error "$1"
-  exit "${2:-1}"
+get_output_dir_name() {
+  echo "$(realpath "${OUTPUT_DIR%/}")/"
 }
 
-log_usage_options_line() {
-  local description="$1"
-  shift
-  local parameters
-  parameters="$(printf "%s, " "$@")"
-  printf "  ${FCOLOR_PURPLE}%-*s${FORMAT_RESET} %s\n" "30" "${parameters::-2}" "$(format_message "$FCOLOR_CYAN" "$description")"
-}
-log_usage_example_line() {
-  local command="$1"
-  format_message "$FCOLOR_PURPLE" "  $command"
-}
+##----Version------------------------------------------------------------------------------------------------------------
 
 get_version_string() {
   # shellcheck disable=SC2317
@@ -221,106 +398,74 @@ get_version() {
   echo "$1" | jq '.header.version'
 }
 
-to_title_case() {
-  echo "$1" | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++){sub(/./,toupper(substr($i,1,1)),$i)}print}'
-}
-
-array_to_string() {
-  echo "$1" | jq -r 'join(".")'
-}
-
 get_shared_version() {
-  local version_file="${INPUT_DIR}version.json"
-  if [[ -f "$version_file" ]]; then
-    array_to_string "$(jq -r '.version' "$version_file")"
+  local _version_file="${INPUT_DIR}version.json"
+  if [[ -f "$_version_file" ]]; then
+    array_to_string "$(jq -r '.version' "$_version_file")"
   else
-    die "Version <b>$version_file</b> file not found" 31
+    die "Version <b>$_version_file</b> file not found" 31
   fi
 }
 
 set_shared_version() {
-  local version_file="${INPUT_DIR}version.json"
-  local version_array="$1"
+  local _version_file="${INPUT_DIR}version.json"
+  local _version_array="$1"
 
   # Create version.json if it doesn't exist
-  if [[ ! -f "$version_file" ]]; then
-    echo '{"version": [1, 0, 0]}' >"$version_file"
+  if [[ ! -f "$_version_file" ]]; then
+    echo '{"version": [1, 0, 0]}' >"$_version_file"
   fi
 
   # Update the version in the shared file
-  local current_content
-  current_content=$(cat "$version_file")
-  echo "$current_content" | jq --argjson ver "$version_array" '.version = $ver' >"$version_file"
+  local _current_content
+  _current_content=$(cat "$_version_file")
+  echo "$_current_content" | jq --argjson ver "$_version_array" '.version = $ver' >"$_version_file"
 }
 
 bump_versions() {
   log_info "Bumping version for BP and RP"
-  local bp_path="${INPUT_DIR}${BP_DIR}manifest.json"
-  local rp_path="${INPUT_DIR}${RP_DIR}manifest.json"
+  local _bp_path="${INPUT_DIR}${BP_DIR}manifest.json"
+  local _rp_path="${INPUT_DIR}${RP_DIR}manifest.json"
 
-  local bp_content
-  bp_content=$(cat "$bp_path")
+  local _bp_content
+  _bp_content=$(cat "$_bp_path")
 
-  local rp_content
-  rp_content=$(cat "$rp_path")
+  local _rp_content
+  _rp_content=$(cat "$_rp_path")
 
-  local bp_uuid
-  bp_uuid="$(echo "$bp_content" | jq -r '.header.uuid')"
+  local _bp_uuid
+  _bp_uuid="$(echo "$_bp_content" | jq -r '.header.uuid')"
 
-  local rp_uuid
-  rp_uuid="$(echo "$rp_content" | jq -r '.header.uuid')"
+  local _rp_uuid
+  _rp_uuid="$(echo "$_rp_content" | jq -r '.header.uuid')"
 
   # Get current shared version and bump it
   play_loading_animation_loop -m "Bumping shared version for BP and RP"
-  local current_shared_version
-  current_shared_version=$(jq -r '.version' "${INPUT_DIR}version.json" 2>/dev/null || echo '[1, 0, 0]')
-  local new_shared_version
-  new_shared_version=$(echo "$current_shared_version" | jq '.[2] += 1')
+  local _current_shared_version
+  _current_shared_version=$(jq -r '.version' "${INPUT_DIR}version.json" 2>/dev/null || echo '[1, 0, 0]')
+  local _new_shared_version
+  _new_shared_version=$(echo "$_current_shared_version" | jq '.[2] += 1')
 
   # Update shared version file
-  set_shared_version "$new_shared_version"
-  kill_loading_animation_loop -m "Bumped version to $(array_to_string "$new_shared_version")"
+  set_shared_version "$_new_shared_version"
+  kill_loading_animation_loop -m "Bumped version to $(array_to_string "$_new_shared_version")"
 
   # Update BP manifest
   play_loading_animation_loop -m "Saving BP version"
-  bp_content=$(echo "$bp_content" | jq --argjson ver "$new_shared_version" '.header.version = $ver')
-  bp_content=$(echo "$bp_content" | jq --argjson ver "$new_shared_version" '(.dependencies[]? | select(.uuid == "'"$rp_uuid"'") | .version) = $ver')
-  echo "$bp_content" >"$bp_path"
+  _bp_content=$(echo "$_bp_content" | jq --argjson ver "$_new_shared_version" '.header.version = $ver')
+  _bp_content=$(echo "$_bp_content" | jq --argjson ver "$_new_shared_version" '(.dependencies[]? | select(.uuid == "'"$_rp_uuid"'") | .version) = $ver')
+  echo "$_bp_content" >"$_bp_path"
   kill_loading_animation_loop -m "Saved BP version"
 
   # Update RP manifest
   play_loading_animation_loop -m "Saving RP version"
-  rp_content=$(echo "$rp_content" | jq --argjson ver "$new_shared_version" '.header.version = $ver')
-  rp_content=$(echo "$rp_content" | jq --argjson ver "$new_shared_version" '(.dependencies[]? | select(.uuid == "'"$bp_uuid"'") | .version) = $ver')
-  echo "$rp_content" >"$rp_path"
+  _rp_content=$(echo "$_rp_content" | jq --argjson ver "$_new_shared_version" '.header.version = $ver')
+  _rp_content=$(echo "$_rp_content" | jq --argjson ver "$_new_shared_version" '(.dependencies[]? | select(.uuid == "'"$_bp_uuid"'") | .version) = $ver')
+  echo "$_rp_content" >"$_rp_path"
   kill_loading_animation_loop -m "Saved RP version"
 }
 
-get_wildcard_filename() {
-  local extension="$1"
-  local suffix="${2:-}"
-  echo -e "$PACKNAME*${suffix}*.${extension}"
-}
-
-get_filename() {
-  local extension="$1"
-  local suffix="${2:-}"
-  local name="$PACKNAME"
-  if [[ $APPEND_VERSION_TO_BUILD_FILE -eq 1 ]]; then
-    name+=" v$(get_shared_version)"
-  fi
-  if [[ $APPEND_TIME_TO_BUILD_FILE -eq 1 ]]; then
-    name+=" $(date +"%Y%m%d%H%M%S")"
-  fi
-  if [[ "$suffix" != "" ]]; then
-    name+=" $suffix"
-  fi
-  echo "${name}.${extension}"
-}
-
-get_output_dir_name() {
-  echo "$(realpath "${OUTPUT_DIR%/}")/"
-}
+##----Build------------------------------------------------------------------------------------------------------------
 
 build_mcaddon() {
   play_loading_animation_loop -m "Preparing MCADDON configuration"
@@ -380,6 +525,8 @@ install_locally() {
   kill_loading_animation_loop -m "Installed RP on local" -s "resource_packs/${MC_PACK_RP_FILE_PATH}"
 }
 
+##----Parser------------------------------------------------------------------------------------------------------------
+
 parse_arguments() {
   while [[ $# -gt 0 ]]; do
     case "$1" in
@@ -426,7 +573,7 @@ parse_arguments() {
   fi
 }
 
-## CONFIGURATION
+## ##----Configuration------------------------------------------------------------------------------------------------------------
 
 declare -r BP_DIR="BP/"
 declare -r RP_DIR="RP/"
@@ -443,6 +590,8 @@ INSTALL_ON_LOCAL=0
 INPUT_DIR=""
 OUTPUT_DIR=""
 MOJANG_DIR="$HOME/Library/Application Support/mcpelauncher/games/com.mojang/"
+
+##----Main------------------------------------------------------------------------------------------------------------
 
 log_title "Minecraft Builder"
 
